[tags]
"place.dungeon" = [
    "person.hero",
    "person.villain",
]
protagonist = [
    "person.hero",
]

[objects]
"person.hero" = [
    "place.dungeon",
    "protagonist",
]
"person.villain" = [
    "place.dungeon",
]
